# Motivating Data {#motivating-data}

```{r, motivating-data-setup}
library(FangPsychometric)
```

- Background of psychometrics
  - Charles Darwin at the core, with the ideas that living organisms adapt to their environment
  - Sir Francis Galton lead the creation of psychometrics
    - "This idea stimulated Galton's interest in the study of human beings and how they differ one from another and, more importantly, how to measure those differences"
    - Galton devised and conducted "mental" tests
  - "Herbart was responsible for creating mathematical models of the mind, which were influential in educational practices in years to come."
  - "E.H. Weber built upon Herbart's work and tried to prove the existence of a psychological threshold, saying that a minimum stimulus was necessary to activate a sensory system"
  - "G.T. Fechner ... devise[d] the law that the strength of a sensation grows as the logarithm of the stimulus intensity"

- Psychometric Experiments
  - "The psychometric function relates an observer’s performance to an independent variable, usually some physical quantity of a stimulus in a psychophysical task" [@wichmann2001a]
  - Studied as early as the late 1800's
  - [@boring1917chart]
  - Perceptual Synchrony
    - Our experiences in life as we age shape the mechanisms of processing multisensory signals
    - Compensation for small temporal differences is beneficial for coherent multisensory experiences, particularly in visual-speech synthesis
    - This gives rise to an idea of the temporal binding window, or the temporal differences for which sensory signals are integrated into a global percept
    - Perceptual synchrony has been previously studied through the point of subjective simultaneity, the physical temporal delay between two signals at which an observer is unsure about their temporal order [@stone2001now]
  - Temporal Sensitivity
    - The temporal binding window is the time span over which sensory signals arising from different modalities appear integrated into a global percept
    - A deficit in temporal sensitivity may lead to a widening of the temporal binding window and cause reduce the ability to segregate unrelated sensory signals
    - In temporal order judgment tasks, the ability to discriminate the timing of multiple sensory signals is referred to as temporal sensitivity, and is studied through the measurement of the just noticeable difference
    - The just noticeable difference is the smallest lapse in time so that a temporal order can just be determined
  - Temporal Recalibration
    - Our perceptual synchrony can be modified through a baseline understanding

- Temporal Order Judgment Psychometric Experiment
  - Setup and Methods
  - Data collection
  - Order of trials
  - The manuscript provided by Ally will really be the main source of content for this section
  - She describes the data collection for three of the sensory tasks
  - Data cleaning and loading
  - Research questions
  
- Observations about the data
  - Outliers and failed experiments
  - balance of classes (male v female, young v middle v older, etc.)
  - Tasks
  - In the workflow section, I will look for and point out any visual trends in the data
