```{r 200-appendix-setup}
```

\setstretch{1.0}

# Appendix A {-}

## One model, Three Implementations {-}

Novice

```{r, eval=FALSE, echo=TRUE}
library(rstanarm)
stan_glmer(cbind(k, n-k) ~ 1 + x + (1 + x | G1) + (1 + x | G2), 
           family = binomial(link = "logit"),
           data = dat)
```

Intermediate

```{r, eval=FALSE, echo=TRUE}
library(rethinking)
ulam(alist(
  k ~ binomial(n, pi)
  logit(pi) <- (a + aG1[G1] + aG2[G2]) + (b + bG1[G1] + bG2[G2]) * x,
  
  a ~ normal(0, 10),
  aG1[G1] ~ normal(0, sd_aG1),
  aG2[G2] ~ normal(0, sd_aG2),
  c(sd_aG1, sd_aG2) ~ half_cauchy(0, 10),

  b ~ normal(0, 10),
  bG1[G1] ~ normal(0, sd_bG1),
  bG2[G2] ~ normal(0, sd_bG2),
  c(sd_bG1, sd_bG2) ~ half_cauchy(0, 10)
), data = dat, log_lik = TRUE)
```

Advanced

```
data{
    int<lower=0> N;
    int<lower=0> N_G1;
    int<lower=0> N_G2;
    int n[N];
    int k[N];
    int G1[N];
    int G2[N];
    int trt[N];
    vector[N] x;
}
parameters{
    real a;
    vector[N_G1] aG1;
    vector[N_G2] aG2;
    real b;
    vector[N_G1] bG1;
    vector[N_G2] bG2;
    real<lower=0> sd_aG1;
    real<lower=0> sd_aG2;
    real<lower=0> sd_bG1;
    real<lower=0> sd_bG2;
}
model{
    vector[N] p;
    a   ~ normal(0, 10);
    aG1 ~ normal(0, sd_aG1);
    aG2 ~ normal(0, sd_aG2);
    b   ~ normal(0, 10);
    bG1 ~ normal(0, sd_bG1);
    bG2 ~ normal(0, sd_bG2);
    sd_aG1 ~ cauchy(0, 10);
    sd_aG2 ~ cauchy(0, 10);
    sd_bG1 ~ cauchy(0, 10);
    sd_bG2 ~ cauchy(0, 10);
    for ( i in 1:N ) {
        p[i] = (a + aG1[G1[i]] + aG2[G2[i]]) + (b + bG1[G1[i]] + bG2[G2[i]]) * x[i];
    }
    k ~ binomial_logit(n , p);
}
```


# Appendix B {-}
