---
title: "Audiovisual - Rethinking"
author: "Alex Knudson"
date: "7/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(FangPsychometric)
library(tidyverse)
library(rethinking)

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

# Data

```{r}
dat <- audiovisual_binomial %>%
  filter(rid != "av-post1-O-f-CE", trial %in% c("pre", "post1")) %>%
  mutate_at(vars("rid", "sid", "trial"), fct_drop) %>%
  mutate(soa = soa / 1000, trt = trial == "post1") %>%
  select(soa, n, k, rid, sid, age_group, trt, age) %>%
  rename(G = age_group, S = sid)
```


```{r, echo=FALSE}
dat %>% slice_sample(n = 10) %>%
  knitr::kable("html")
```


## Complete Pooling

```{r}
aPbx_notrt_noage_nosub_nolapse <- ulam(alist(
  k ~ binomial_logit(n, p),
  p <- a + b*soa,
  a ~ normal(0, 10),
  b ~ normal(0, 10)
), data=dat, log_lik=TRUE, chains=4, cores=4, iter=2500, refresh=2500)
```

```{r}
bxMa_notrt_noage_nosub_nolapse <- ulam(alist(
  k ~ binomial_logit(n, p),
  p <- b*(soa - a),
  a ~ normal(0, 1),
  b ~ normal(0, 30)
), data=dat, log_lik=TRUE, chains=4, cores=4, iter=2500, refresh=2500)
```

## No Pooling

## Partial Pooling

```{r}
pp_ln <- alist(
  k ~ binomial_logit(n, p),
  p <- exp(b + bG[G] + bS[S] + (bT + bTG[G] + bTS[S])*trt) * (soa - (a + aG[G] + aS[S] + (aT + aTG[G] + aTS[S])*trt)),
  
  a ~ normal(0, 0.1),
  aG[G] ~ normal(0, sd_aG),
  aS[S] ~ normal(0, sd_aS),
  
  aT ~ normal(0, 0.1),
  aTG[G] ~ normal(0, sd_aTG),
  aTS[S] ~ normal(0, sd_aTS),
  
  b ~ normal(2, 1),
  bG[G] ~ normal(0, sd_bG),
  bS[S] ~ normal(0, sd_bS),
  
  bT ~ normal(0, 1),
  bTG[G] ~ normal(0, sd_bTG),
  bTS[S] ~ normal(0, sd_bTS),
  
  c(sd_aG, sd_aS) ~ half_cauchy(0, 2.5),
  c(sd_aTG, sd_aTS) ~ half_cauchy(0, 2.5),
  
  c(sd_bG, sd_bS) ~ half_cauchy(0, 5),
  c(sd_bTG, sd_bTS) ~ half_cauchy(0, 5)
)

fit_pp_ln <- ulam(pp_ln, data = dat, log_lik = TRUE,
                  chains = 8, cores = 8, iter = 2500)

post <- extract.samples(fit_pp_ln)
```


```{r}
mean(post$a)
mean(post$aT)
mean(post$b)
mean(post$bT)


sd(post$a)
sd(post$T)
sd(post$b)
sd(post$bT)
```

