---
title: "Outline"
author: "Alex Knudson"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Introduction
  - Conventional (classical) methods
  - Bayesian statistics
  - MCMC enables modern Bayesian models
  - Organization
- Methods Background
  - Fitting PFs using GLMs
  - Bayesian multilevel modeling
  - Hamiltonian Monte Carlo and NUTS
  - Model checking
  - Predictive performance
  - Modeling workflow
- Data Background
  - Psychometric experiments
  - Temporal order judgment data
  - Data visualizations and quirks
- Workflow
  - Modeling psychometric quantities
  - Iteration 1 (base model)
  - Iteration 2 (add age/block)
  - Iteration 3 (add age/block interaction)
  - Iteration 4 (add lapse rate)
  - Iteration 5 (add subject level)
- Results
  - Perceptual synchrony
  - Temporal sensitivity
  - Lapse rates
  - Subject level predictions
- Discussion/Conclusion
  - TOJ Experimental Design
  - Model comparison vs. selection
  - Rehash of results
  - Point out my direct contributions
  - Future work
  - Final word
- Appendix
  - Developing a model
  - Data cleaning and reproducibility
